import {
  buildChatInferenceFunctionsForOpenAI,
  type ChatPromptContext,
  type OpenAIInterface as OpenAIInterfaceForChat,
} from "^/openai/openai-chat.ts";
import {
  buildImageInferenceFunctionsForOpenAI,
  type ImagePromptContext,
  type OpenAIInterface as OpenAIInterfaceForImage,
} from "^/openai/openai-image.ts";
import {
  type InferenceFn,
  type InferenceParams,
  initPromptBuilder,
  type TemplateArgs,
} from "^/prompt.ts";
import type { ExtractPlaceholders, IfNever } from "^/template.ts";

export { type ChatPromptContext } from "^/openai/openai-chat.ts";
export { type ImagePromptContext } from "^/openai/openai-image.ts";

/**
 * The minimum interface that an OpenAI client must implement to be used with this library.
 */
export type OpenAIInterface<Message> =
  & OpenAIInterfaceForChat<Message>
  & OpenAIInterfaceForImage;

/**
 * Builds inference functions for an OpenAI client. Pass in the OpenAI client after it has been
 * initialized, and the types will be inferred.
 */
export const buildInferenceFunctionsForOpenAI:
  BuildInferenceFunctionsForOpenAI = <
    Message,
    OpenAI extends OpenAIInterface<Message>,
  >(
    openai: OpenAI,
  ) => {
    const initChatPromptBuilder = initPromptBuilder<
      ChatPromptContext<Message, OpenAI>
    >;
    const initImagePromptBuilder = initPromptBuilder<
      ImagePromptContext<OpenAI>
    >;
    return {
      initChatPromptBuilder,
      initImagePromptBuilder,
      ...buildChatInferenceFunctionsForOpenAI(openai),
      ...buildImageInferenceFunctionsForOpenAI(openai),
    };
  };

// Generated by dnt
type BuildInferenceFunctionsForOpenAI = <
  Message,
  OpenAI extends OpenAIInterface<Message>,
>(openai: OpenAI) => {
  mergeContext: (
    params: InferenceParams<ImagePromptContext<OpenAI>>,
  ) => ImagePromptContext<OpenAI>;
  inferImageRaw: (
    renderedTemplate: string,
    { body, options }: ImagePromptContext<OpenAI>,
  ) => Promise<(string | undefined)[]>;
  inferImage: (
    params: InferenceParams<ImagePromptContext<OpenAI>>,
  ) => Promise<(string | undefined)[]>;
  respondWithImage: (
    format?: "url" | "b64_json",
  ) => (
    params: InferenceParams<ImagePromptContext<OpenAI>>,
  ) => Promise<(string | undefined)[]>;
  mergeChatContext: (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => ChatPromptContext<unknown, OpenAI>;
  mergeChatContextAndMessages: (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => ChatPromptContext<unknown, OpenAI>;
  inferChatRaw: (
    messages: unknown[],
    { body, options }: ChatPromptContext<unknown, OpenAI>,
  ) => Promise<
    Awaited<
      ReturnType<OpenAI["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  inferChoice: (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => Promise<
    Awaited<
      ReturnType<OpenAI["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  inferJson: <Schema extends import("zod").ZodType>(
    schema: Schema,
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => Promise<import("zod").TypeOf<Schema>>;
  respondWithChoice: () => (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => Promise<
    Awaited<
      ReturnType<OpenAI["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  respondWithText: () => (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => Promise<string | null>;
  respondWithJson: <Schema extends import("zod").ZodType>(
    schema: Schema,
  ) => (
    params: InferenceParams<
      ChatPromptContext<unknown, OpenAI>
    >,
  ) => Promise<import("zod").TypeOf<Schema>>;
  initChatPromptBuilder: (
    contextFromBuilder: ChatPromptContext<Message, OpenAI>,
  ) => <
    TemplateString extends string,
    Infer extends InferenceFn<
      ChatPromptContext<Message, OpenAI>,
      ExtractPlaceholders<TemplateString>,
      any
    >,
  >(
    template: TemplateString,
    infer: Infer,
    defaultRequest?: Partial<ChatPromptContext<Message, OpenAI>> | undefined,
  ) => (
    ...args: IfNever<
      ExtractPlaceholders<TemplateString>,
      [context?: Partial<ChatPromptContext<Message, OpenAI>> | undefined],
      [
        templateArgs: TemplateArgs<
          ExtractPlaceholders<TemplateString>
        >,
        context?: Partial<ChatPromptContext<Message, OpenAI>> | undefined,
      ]
    >
  ) => Promise<Awaited<ReturnType<Infer>>>;
  initImagePromptBuilder: (
    contextFromBuilder: ImagePromptContext<OpenAI>,
  ) => <
    TemplateString extends string,
    Infer extends InferenceFn<
      ImagePromptContext<OpenAI>,
      ExtractPlaceholders<TemplateString>,
      any
    >,
  >(
    template: TemplateString,
    infer: Infer,
    defaultRequest?: Partial<ImagePromptContext<OpenAI>> | undefined,
  ) => (
    ...args: IfNever<
      ExtractPlaceholders<TemplateString>,
      [context?: Partial<ImagePromptContext<OpenAI>> | undefined],
      [
        templateArgs: TemplateArgs<
          ExtractPlaceholders<TemplateString>
        >,
        context?: Partial<ImagePromptContext<OpenAI>> | undefined,
      ]
    >
  ) => Promise<Awaited<ReturnType<Infer>>>;
};
