import {
  buildChatInferenceFunctionsForTogether,
  type ChatPromptContext,
  type TogetherInterface as TogetherInterfaceForChat,
} from "^/together/together-chat.ts";
import {
  buildImageInferenceFunctionsForTogether,
  type ImagePromptContext,
  type TogetherInterface as TogetherInterfaceForImage,
} from "^/together/together-image.ts";
import {
  type InferenceFn,
  type InferenceParams,
  initPromptBuilder,
  type TemplateArgs,
} from "^/prompt.ts";
import type { ExtractPlaceholders, IfNever } from "^/template.ts";

export { type ChatPromptContext } from "^/together/together-chat.ts";
export { type ImagePromptContext } from "^/together/together-image.ts";

/**
 * The minimum interface that a TogetherAI client must implement to be used with this library.
 */
export type TogetherInterface<Message> =
  & TogetherInterfaceForChat<Message>
  & TogetherInterfaceForImage;

/**
 * Builds inference functions for a TogetherAI client. Pass in the Together client after it has
 * been initialized, and the types will be inferred.
 */
export const buildInferenceFunctionsForTogether:
  BuildInferenceFunctionsForTogether = <
    Message,
    Together extends TogetherInterface<Message>,
  >(
    together: Together,
  ) => {
    const initChatPromptBuilder = initPromptBuilder<
      ChatPromptContext<Message, Together>
    >;
    const initImagePromptBuilder = initPromptBuilder<
      ImagePromptContext<Together>
    >;
    return {
      initChatPromptBuilder,
      initImagePromptBuilder,
      ...buildChatInferenceFunctionsForTogether(together),
      ...buildImageInferenceFunctionsForTogether(together),
    };
  };

// Generated by dnt

type BuildInferenceFunctionsForTogether = <
  Message,
  Together extends TogetherInterface<Message>,
>(together: Together) => {
  mergeContext: (
    params: InferenceParams<
      ImagePromptContext<Together>
    >,
  ) => ImagePromptContext<Together>;
  inferImageRaw: (
    renderedTemplate: string,
    { body, options }: ImagePromptContext<Together>,
  ) => Promise<(string | undefined)[]>;
  inferImage: (
    params: InferenceParams<
      ImagePromptContext<Together>
    >,
  ) => Promise<(string | undefined)[]>;
  respondWithImage: (
    format?: "url" | "b64_json",
  ) => (
    params: InferenceParams<
      ImagePromptContext<Together>
    >,
  ) => Promise<(string | undefined)[]>;
  mergeChatContext: (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => ChatPromptContext<unknown, Together>;
  mergeChatContextAndMessages: (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => ChatPromptContext<unknown, Together>;
  inferChatRaw: (
    messages: unknown[],
    { body, options }: ChatPromptContext<unknown, Together>,
  ) => Promise<
    Awaited<
      ReturnType<Together["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  inferChoice: (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => Promise<
    Awaited<
      ReturnType<Together["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  inferJson: <Schema extends import("zod").ZodType>(
    schema: Schema,
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => Promise<import("zod").TypeOf<Schema>>;
  respondWithChoice: () => (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => Promise<
    Awaited<
      ReturnType<Together["chat"]["completions"]["create"]>
    >["choices"][number]
  >;
  respondWithText: () => (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => Promise<string | null | undefined>;
  respondWithJson: <Schema extends import("zod").ZodType>(
    schema: Schema,
  ) => (
    params: InferenceParams<
      ChatPromptContext<unknown, Together>
    >,
  ) => Promise<import("zod").TypeOf<Schema>>;
  initChatPromptBuilder: (
    contextFromBuilder: ChatPromptContext<Message, Together>,
  ) => <
    TemplateString extends string,
    Infer extends InferenceFn<
      ChatPromptContext<Message, Together>,
      ExtractPlaceholders<TemplateString>,
      any
    >,
  >(
    template: TemplateString,
    infer: Infer,
    defaultRequest?: Partial<ChatPromptContext<Message, Together>> | undefined,
  ) => (
    ...args: IfNever<
      ExtractPlaceholders<TemplateString>,
      [context?: Partial<ChatPromptContext<Message, Together>> | undefined],
      [
        templateArgs: TemplateArgs<
          ExtractPlaceholders<TemplateString>
        >,
        context?: Partial<ChatPromptContext<Message, Together>> | undefined,
      ]
    >
  ) => Promise<Awaited<ReturnType<Infer>>>;
  initImagePromptBuilder: (
    contextFromBuilder: ImagePromptContext<Together>,
  ) => <
    TemplateString extends string,
    Infer extends InferenceFn<
      ImagePromptContext<Together>,
      ExtractPlaceholders<TemplateString>,
      any
    >,
  >(
    template: TemplateString,
    infer: Infer,
    defaultRequest?: Partial<ImagePromptContext<Together>> | undefined,
  ) => (
    ...args: IfNever<
      ExtractPlaceholders<TemplateString>,
      [context?: Partial<ImagePromptContext<Together>> | undefined],
      [
        templateArgs: TemplateArgs<
          ExtractPlaceholders<TemplateString>
        >,
        context?: Partial<ImagePromptContext<Together>> | undefined,
      ]
    >
  ) => Promise<Awaited<ReturnType<Infer>>>;
};
